{% set name = "doped" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SMTG-UCL/doped/archive/{{ version }}.tar.gz
  sha256: 73a365e9beb67206668e1ee955da7f58084e5df1356c0bec027899cc9d8eb894


# PyPI (no test files...)
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: a1eca51ccdc1fdc9e71e39d1f864c4cf472c7452fa86c717ab192688afa9a933

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - tabulate
    - matplotlib-base
    - numpy >=1.21.0
    - pymatgen >=2023.5.8  # imposed by pymatgen-analysis-defects
    - pymatgen-analysis-defects >=2023.8.22
    - monty
    - shakenbreak >=3.0.0
    - pandas

test:
  imports:
    - doped

about:
  home: https://github.com/SMTG-UCL/doped
  license: MIT
  license_file: LICENSE
  summary: Python package to setup, process and analyse solid-state defect calculations with VASP
  description: |
    doped is a Python package for setting up, processing, and analyzing solid-state defect calculations with VASP.
  doc_url: https://doped.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-UCL/doped

extra:
  recipe-maintainers:
    - kavanase
