{% set name = "doped" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SMTG-UCL/doped/archive/{{ version }}.tar.gz
  sha256: 5adec1e92ad0eb03cbfcfb77f6fffb5e2f2e1389444f317b15e818c821f87753


# PyPI (no test files...)
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: a1eca51ccdc1fdc9e71e39d1f864c4cf472c7452fa86c717ab192688afa9a933

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - tabulate
    - matplotlib-base >=3.5.2
    - numpy >=1.21.0
    - pymatgen >=2023.11.12  # limiting factor: POTCAR_STATS_PATH available from pymatgen.io.vasp.inputs
    - spglib ==2.0.2  # dependent of pymatgen, but explicitly set to 2.0.2 here to avoid unnecessary warnings
      # see https://github.com/spglib/spglib/issues/338; remove this limit when issue resolved
    - pymatgen-analysis-defects >=2023.8.22
    - shakenbreak >=3.3.1
    - pandas
    - filelock
    # - pydefect  # not available on conda-forge currently, will update in future if it is. User installation instructions say to install afterwards with pip

test:
  imports:
    - doped

about:
  home: https://github.com/SMTG-Bham/doped
  license: MIT
  license_file: LICENSE
  summary: Python package to setup, process and analyse solid-state defect calculations with VASP
  description: |
    doped is a Python software for the generation, pre-/post-processing and analysis of defect supercell calculations, implementing the defect simulation workflow in an efficient, reproducible, user-friendly yet powerful and fully-customisable manner.
  doc_url: https://doped.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-Bham/doped

extra:
  recipe-maintainers:
    - kavanase
