{% set name = "doped" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SMTG-UCL/doped/archive/{{ version }}.tar.gz
  sha256: 2319586f6ca12ba10c7f28ab17c2388224e8c490b9b8d674e44760bde8d52a6f


# PyPI (no test files...)
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: a1eca51ccdc1fdc9e71e39d1f864c4cf472c7452fa86c717ab192688afa9a933

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.11
  run:
    - python >=3.7,<3.11
    - tabulate
    - matplotlib-base
    - numpy >=1.21.0
    - pymatgen <2022.8.23
    - monty
    - packaging
    - pandas

test:
  imports:
    - doped

about:
  home: https://github.com/SMTG-UCL/doped
  license: MIT
  license_file: LICENSE
  summary: Python package to setup, process and analyse solid-state defect calculations with VASP
  description: |
    DOPED is a Python package for setting up, processing, and analyzing solid-state defect calculations with VASP.
  dev_url: https://github.com/SMTG-UCL/doped

extra:
  recipe-maintainers:
    - kavanase
