{% set name = "doped" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SMTG-Bham/doped/archive/{{ version }}.tar.gz
  sha256: 2683bd060ec99a3d705463de4549a256d3142a6d8ebd4fa8030927d31ed3d44a

# PyPI (no test files...)
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: a1eca51ccdc1fdc9e71e39d1f864c4cf472c7452fa86c717ab192688afa9a933

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tabulate
    - matplotlib-base >=3.5.2
    - numpy >=1.21.0
    - pymatgen >=2025.10.7  # LinearAssignment refactoring
    - pymatgen-analysis-defects >=2023.8.22
    - shakenbreak >=3.3.4  # oxi-state functions renaming
    - pandas
    - filelock
    - cmcrameri >=1.4  # for colour-maps; >=1.4 required for cmcrameri.cm.cmaps definition
    - matplotlib-label-lines  # for labelling lines in matplotlib plots
    - dscribe  # for defect site guessing using SOAP analysis
    # - pydefect  # not available on conda-forge currently, will update in future if it is. User installation instructions say to install afterwards with pip

test:
  requires:
    - python {{ python_min }}
 imports:
   - doped

about:
  home: https://github.com/SMTG-Bham/doped
  license: MIT
  license_file: LICENSE
  summary: Python package to setup, process and analyse solid-state defect calculations/
  description: |
    doped is a Python software for the generation, pre-/post-processing and analysis of defect supercell calculations, implementing the defect simulation workflow in an efficient, reproducible, user-friendly yet powerful and fully-customisable manner.
  doc_url: https://doped.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-Bham/doped

extra:
  recipe-maintainers:
    - kavanase
